# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields: {
  matomo_base_url: "{{ env.MATOMO_BASE_URL }}",
  matomo_api_key: "{{ env.MATOMO_API_KEY }}",
  matomo_site_id: "9",
  matomo_date_range: "last30",
  matomo_active_view: "metrics" # valid: metrics, landing_pages
}

# override variables
variables:
  trmnl: {
    plugin_settings: {
      instance_name: "Matomo Analytics"
    }
  }
