---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: post
polling_url: |
  {{ matomo_base_url }}/?module=API&format=JSON&method=API.getMatomoVersion
  {{ matomo_base_url }}/?module=API&method=VisitsSummary.get&idSite={{ matomo_site_id }}&period=day&date=last30&format=JSON
  {{ matomo_base_url }}/?module=API&method=SitesManager.getSiteFromId&idSite={{ matomo_site_id }}&format=JSON
polling_headers: ''
polling_body: 'token_auth={{ matomo_api_key }}'
id: 97234
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  description: Displays web analytics from Matomo for a selected Site.
  github_url: https://github.com/stephenyeargin/trmnl-matomo
  learn_more_url: https://matomo.org/
  email_address: stephen@yearg.in
- keyname: matomo_api_key
  field_type: string
  name: Matomo API Key
  description: User's API Key for Matomo
  placeholder: user_somelongstringoeshere
- keyname: matomo_base_url
  field_type: url
  name: Matomo Base URL
  description: The URL of your Matomo installation
  placeholder: https://analytics.example.com/matomo
  help_text: Please include http:// or https://
- keyname: matomo_site_id
  field_type: number
  placeholder: '1'
  name: Site ID
  description: The integer ID of the desired site for reporting
name: Matomo Analytics
refresh_interval: 1440
